language:
  - python

python:
  - "3.6"

install:
  - pip install flask
  - pip install flask_wtf
  - pip install pip install sqlalchemy
  - pip install flake8

services:
  - sqlalchemy
script:
  - python app.py

after_success:
  - flake8 --max-line-length 100 --ignore=E121,E123,E126,E221,E222,E225,E226,E242,E701,E702,E704,E731,W503 .

notifications:
  email: false